export { default as LandingPage } from './landingPage'
export { default as LoginPage } from './login'
export { default as SignUpPage } from './Signup'
export { default as UserPage } from './User'
export { default as DashboardPage} from './Dashboard'